version: '3'
services:
  aspnet_core_react_redux-db:
    container_name: aspnet_core_react_redux-db
    hostname: sql-server
    build:
      context: .
      dockerfile: docker/sql-server/Dockerfile
    volumes:
      - ./docker/sql-server/initdb:/usr/local/bin/initdb
    expose:
      - 1433
    ports:
      - 1433:1433
    restart: always
  aspnet_core_react_redux:
    build:
      context: .
      dockerfile: docker/dotnet/Dockerfile
    environment:
      APP_DB_CONNECTION_STRING: ${APP_DB_CONNECTION_STRING}
    volumes:
      - aspnet_core_react_redux-host:/app/:nocopy
    ports:
      - 5000:5000
      - 5001:5001
    expose:
      - 5000
      - 5001
    restart: always
    depends_on:
     - aspnet_core_react_redux-db
volumes:
  aspnet_core_react_redux-host:
    external: true