version: '3'
services:
  aspnet_core_react_redux-db:
    build:
      context: .
      dockerfile: docker/sql-server/Dockerfile
    expose:
      - 1433
    ports:
      - 1433:1433
    restart: always
  aspnet_core_react_redux:
    build:
      context: .
      dockerfile: docker/dotnet/Dockerfile
    environment:
      APP_DB_CONNECTION_STRING: ${APP_DB_CONNECTION_STRING}
    volumes:
      - .:/app
      - /app/obj
    ports:
      - 5000:5000
      - 5001:5001
    expose:
      - 5000
      - 5001
    restart: always
    depends_on:
     - aspnet_core_react_redux-db