#!/bin/bash
/opt/mssql-tools/bin/sqlcmd \
   -S localhost -U SA -P "$SA_PASSWORD" \
   -Q "CREATE DATABASE $APP_DB"

/opt/mssql-tools/bin/sqlcmd \
   -S localhost -U SA -P "$SA_PASSWORD" \
   -Q "CREATE LOGIN $APP_DB_ACCOUNT WITH PASSWORD='$APP_DB_ACCOUNT_PASSWORD'"

/opt/mssql-tools/bin/sqlcmd \
   -S localhost -U SA -P "$SA_PASSWORD" \
   -d $APP_DB \
   -Q "CREATE USER $APP_DB_ACCOUNT FROM LOGIN $APP_DB_ACCOUNT;"

/opt/mssql-tools/bin/sqlcmd \
   -S localhost -U SA -P "$SA_PASSWORD" \
   -d $APP_DB \
   -Q "exec sp_addrolemember 'db_owner', '$APP_DB_ACCOUNT'"