#!/bin/bash

echo "Creating $APP_DB..."
/opt/mssql-tools/bin/sqlcmd \
   -S localhost -U SA -P "$SA_PASSWORD" \
   -Q "IF NOT EXISTS(SELECT * FROM sys.sysdatabases WHERE name = N'$APP_DB') BEGIN CREATE DATABASE $APP_DB END"

echo "Creating login $APP_DB_ACCOUNT..."
/opt/mssql-tools/bin/sqlcmd \
   -S localhost -U SA -P "$SA_PASSWORD" \
   -Q "IF NOT EXISTS(SELECT * FROM sys.sql_logins WHERE name = N'$APP_DB_ACCOUNT') BEGIN CREATE LOGIN $APP_DB_ACCOUNT WITH PASSWORD='$APP_DB_ACCOUNT_PASSWORD' END"

echo "Creating user $APP_DB_ACCOUNT in $APP_DB..."
/opt/mssql-tools/bin/sqlcmd \
   -S localhost -U SA -P "$SA_PASSWORD" \
   -d $APP_DB \
   -Q "IF NOT EXISTS(SELECT * FROM sys.sysusers WHERE name = N'app_service') BEGIN CREATE USER $APP_DB_ACCOUNT FROM LOGIN $APP_DB_ACCOUNT END"

echo "Assigning user $APP_DB_ACCOUNT db_owner to $APP_DB..."
/opt/mssql-tools/bin/sqlcmd \
   -S localhost -U SA -P "$SA_PASSWORD" \
   -d $APP_DB \
   -Q "IF IS_ROLEMEMBER ('db_owner','$APP_DB_ACCOUNT') = 0 BEGIN exec sp_addrolemember 'db_owner', '$APP_DB_ACCOUNT' END"